name: kidscounting
description: Number Learning

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.15.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/splash-screen.png
    - assets/images/number_counting_bg.png
    - assets/images/number-title.png
    - assets/images/number-btn-counting.png
    - assets/images/number-btn-pic.png
    - assets/images/number-btn-puzzle.png
    - assets/images/number_counting_title.png
    - assets/images/number_counting_clickToPlay.png
    - assets/images/number-1.png
    - assets/images/number-2.png
    - assets/images/number-3.png
    - assets/images/number-4.png
    - assets/images/number-5.png
    - assets/images/number-6.png
    - assets/images/number-7.png
    - assets/images/number-8.png
    - assets/images/number-9.png
    - assets/images/number-10.png
    - assets/images/btn-mute.png
    - assets/images/btn-unmute.png
    - assets/images/btn-repeat.png
    - assets/images/object-1.png
    - assets/images/object-2.png
    - assets/images/object-3.png
    - assets/images/object-4.png
    - assets/images/object-5.png
    - assets/images/object-6.png
    - assets/images/object-7.png
    - assets/images/object-8.png
    - assets/images/object-9.png
    - assets/images/object-10.png
    - assets/audio/0.mp3
    - assets/audio/1.mp3
    - assets/audio/2.mp3
    - assets/audio/3.mp3
    - assets/audio/4.mp3
    - assets/audio/5.mp3
    - assets/audio/6.mp3
    - assets/audio/7.mp3
    - assets/audio/8.mp3
    - assets/audio/9.mp3
    - assets/audio/10.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
